version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: military_assets_db
    environment:
      POSTGRES_DB: military_assets_db
      POSTGRES_USER: military_user
      POSTGRES_PASSWORD: military_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - military_network

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: military_assets_backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://military_user:military_password@postgres:5432/military_assets_db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - military_network
    command: npm run dev

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: military_assets_frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
      REACT_APP_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - military_network
    command: npm start

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: military_assets_redis
    ports:
      - "6379:6379"
    networks:
      - military_network

volumes:
  postgres_data:

networks:
  military_network:
    driver: bridge 